### ISSUE TITLE
Power Module

### ISSUE THREAD

**Issue by evanugarte** [SJSURoboticsTeam/missioncontrol2019#9]
**Control:**
- Main Power on/off
- Individual Component Power on/off

**Feedback:**
- Current Levels of Individual Output Channels
- Battery Voltage

**Comment by evanugarte** [comment]
haha

**Comment by qwook** [comment]
thats nhat cool

**Comment by nattstack** [comment]
Lmao I installed the new GitHub mobile app and thought all the issues were made by me 🤣

Recommend to use GitHub App to automatically close stale issues older than 4 months. 

https://github.com/apps/stale
